name: library_management
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:  

  cupertino_icons: ^1.0.2
  flutterbook: ^0.1.7
  md2_tab_indicator: ^1.0.2
  material_design_icons_flutter: ^5.0.6996
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4
  flutter_local_notifications: ^11.0.1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/google_logo.png
    - assets/profile.png
    - assets/cook.png
    - assets/dictonary.png
    - assets/electrical.png
    - assets/reaserch.png
    - assets/Thesis-bro.png
    - assets/commerce.png
    - assets/icon1.png
    - assets/back.png
    - assets/dark.png
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png

